### ISSUE TITLE
Circular dependency check is missing when removing node

### ISSUE THREAD

**Issue by nbcss** [fin444/ability-bonsai#5]
The ability tree did not check circular dependency when removing an ability node, which may produce an invalid tree. 

For example, in the warrior ability tree: 
1. Active nodes Water Mastery, Half-Moon Swipe, Counter, Flying Kick to get 4 Battle Monk points. 
2. Active node Ambidextrous. 
3. Active node Collide to get one extra Battle Monk point. 
4. Active node Whirlwind Strike (it requires 5 Battle Monk points). 
5. Active node Spirit of the Rabbit to get one extra Battle Monk point. 
6. Remove node Collide: **the Whirlwind Strike is still active due to circular dependency from Spirit of the Rabbit.**

**Comment by fin444** [comment]
This project has been abandoned
